images:
- name: go
  description: Go (golang) is a general purpose, higher-level, imperative programming language.
  provides:
  - go
  image: docker.io/golang:1.13-buster
  cache:
  - name: golang-13
    directory: /go/pkg
- name: go-bindata
  description: This package converts any file into manageable Go source code. Useful for embedding binary data into a go program. The file data is optionally gzip compressed before being converted to a raw byte slice.
  provides:
  - go-bindata
  image: docker.io/envcli/go-bindata:latest
