images:
- name: go
  description: Go (golang) is a general purpose, higher-level, imperative programming language.
  provides:
  - go
  image: quay.io/cidverse/build-go:1.20
  cache:
  - name: golang
    directory: /go/pkg
