# Image
image: docker.io/envcli/envcli:latest

# Services
services:
- docker:stable-dind

# Stages
stages:
- test
- build
- release

# Run Tests
Test EnvCLI:
  stage: test
  script:
  - envcli run -env GOOS=linux --env GOARCH=amd64 --env CGO_ENABLED=0 go test src/*.go
  - envcli run -env GOOS=linux --env GOARCH=amd64 --env CGO_ENABLED=0 go test pkg/container_runtime/*.go
  only:
  - master
  - develop

# Run Builds
Build EnvCLI:
  stage: build
  script:
  - envcli run --env GOOS=windows --env GOARCH=386 --env CGO_ENABLED=0 go build -o build/envcli_windows_386 -ldflags="-w" src/*
  - envcli run --env GOOS=windows --env GOARCH=amd64 --env CGO_ENABLED=0 go build -o build/envcli_windows_amd64 -ldflags="-w" src/*
  - envcli run --env GOOS=linux --env GOARCH=386 --env CGO_ENABLED=0 go build -o build/envcli_linux_386 -ldflags="-w" src/*
  - envcli run --env GOOS=linux --env GOARCH=amd64 --env CGO_ENABLED=0 go build -o build/envcli_linux_amd64 -ldflags="-w" src/*
  - envcli run --env GOOS=darwin --env GOARCH=386 --env CGO_ENABLED=0 go build -o build/envcli_darwin_386 -ldflags="-w" src/*
  - envcli run --env GOOS=darwin --env GOARCH=amd64 --env CGO_ENABLED=0 go build -o build/envcli_darwin_amd64 -ldflags="-w" src/*
  only:
  - master
  - develop
  artifacts:
    paths:
    - build/
    expire_in: 1 week
