# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#

# Ignore modules that are part of this project
ignored = ["github.com/EnvCLI/EnvCLI*"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.4"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"
