site_name: EnvCLI
repo_url: https://github.com/philippheuer/envcli
theme: readthedocs
docs_dir: docs
pages:
- Overview: 'index.md'
- Usage Examples:
    - 'Golang': 'examples/golang.md'
    - 'Node': 'examples/node.md'
- Configuration:
    - 'EnvCLI.yml Specification': 'config/envcli-yml-specification.md'
    - 'Project Config': 'config/project-config.md'
    - 'Global Config': 'config/global-config.md'
- For Contributors:
    - 'Overview & Collobaration': 'contributors/overview.md'
    - 'Build & Test EnvCLI': 'contributors/build-test.md'
- Changelog & Migration:
    - 'Overview & Collobaration': 'changelog/overview.md'
    - '0.1.0': 'changelog/0-1-0.md'
    - '0.2.0': 'changelog/0-2-0.md'
