site_name: EnvCLI
repo_url: https://github.com/philippheuer/envcli
theme: readthedocs
docs_dir: docs
pages:
- Overview: 'index.md'
- Usage Examples:
    - 'Golang': 'examples/golang.md'
    - 'Node': 'examples/node.md'
- Features:
    - 'Aliases (omit envcli run)': 'features/alias.md'
    - 'Official Docker Image': 'features/docker.md'
    - 'Use in CI/CD with GitLab or simelar': 'features/ci.md'
- Configuration:
    - 'EnvCLI.yml Specification': 'config/envcli-yml-specification.md'
    - 'Project Config': 'config/project-config.md'
    - 'Global Config': 'config/global-config.md'
- For Contributors:
    - 'Overview & Collobaration': 'contributors/overview.md'
    - 'Build & Test EnvCLI': 'contributors/build-test.md'
